DROP TABLE IF EXISTS Board;

CREATE TABLE Board (
	board_no INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	content TEXT NULL,
	writer VARCHAR(50) NOT NULL,
	reg_date TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY(board_no)
);